- type: replace
  path: /releases?/name=cf-rabbitmq-multitenant-broker?
  value:
    name: cf-rabbitmq-multitenant-broker
    version: 95.0.0
    url: https://cf-rabbitmq-multitenant-broker-genesis-releases.s3.amazonaws.com/cf-rabbitmq-multitenant-broker-95.0.0.tgz
    sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
