- type: replace
  path: /releases?/name=cf-rabbitmq?
  value:
    name: cf-rabbitmq
    version: 387.0.0
    url: https://cf-rabbitmq-genesis-releases.s3.amazonaws.com/cf-rabbitmq-387.0.0.tgz
    sha1: d59134e74eb5488a2d2a430184e64319f0951b2b
