- type: replace
  path: /releases?/name=cf-rabbitmq?
  value:
    name: cf-rabbitmq
    version: 336.0.0
    url: https://bosh.io/d/github.com/pivotal-cf/cf-rabbitmq-release?v=336.0.0
    sha1: cf03e73395d376d8122b6495dc5eed2b10e92f2f
