- type: replace
  path: /releases?/name=cf-rabbitmq?
  value:
    name: cf-rabbitmq
    version: 614.0.0
    url: https://github.com/cloudfoundry-community/cf-rabbitmq-release/releases/download/v614.0.0/cf-rabbitmq-614.0.0.tgz
    sha1: fa99fd8cae05d3af0d8cbd287de8cf0258f2d521
