- type: replace
  path: /releases?/name=cf-rabbitmq?
  value:
    name: cf-rabbitmq
    version: 615.0.0
    url: https://github.com/cloudfoundry-community/cf-rabbitmq-release/releases/download/v615.0.0/cf-rabbitmq-615.0.0.tgz
    sha1: cb62013f5c460ad1f30063090e993e95829ea5a3
