- type: replace
  path: /releases?/name=cf-rabbitmq?
  value:
    name: cf-rabbitmq
    version: 410.0.0
    url: https://cf-rabbitmq-genesis-releases.s3.amazonaws.com/cf-rabbitmq-410.0.0.tgz
    sha1: 188506761989eeb5bdd400dbf41fd6add8ff6071
