- type: replace
  path: /releases?/name=cf-rabbitmq?
  value:
    name: cf-rabbitmq
    version: 404.0.0
    url: https://cf-rabbitmq-genesis-releases.s3.amazonaws.com/cf-rabbitmq-404.0.0.tgz
    sha1: 678ab3f9654a8c7eee14ecf77a455ef1ba1a53f5
