- type: replace
  path: /releases?/name=haproxy?
  value:
    name: haproxy
    version: 11.8.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=11.8.0
    sha1: 386f80c2e64775623680798f73de8f78bdfe9be9
