- type: replace
  path: /releases?/name=loggregator-agent?
  value:
    name: loggregator-agent
    version: 6.3.8
    url: https://bosh.io/d/github.com/cloudfoundry/loggregator-agent-release?v=6.3.8
    sha1: e294666956297dddc27dd40c0bc6a80414dd24f1
