meta:
  releases:
  - name:    cf-rabbitmq
    version: 312.0.0
    url:     https://bosh.io/d/github.com/pivotal-cf/cf-rabbitmq-release?v=312.0.0
    sha1:    1a90f68f8a0e353397eea2ef4ccc0a0bb50c5596

  - name:    cf-rabbitmq-multitenant-broker
    version: 80.0.0
    url:     https://bosh.io/d/github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release?v=80.0.0
    sha1:    d256a6ba4d94254284930ebd7f0006315884437d

  - name:    cf-rabbitmq-smoke-tests
    version: 65.0.0
    url:     https://bosh.io/d/github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release?v=64.0.0
    sha1:    add77ac51dba0c7cbda195d138bb80765d2a948a

  - name:    bpm
    version: 1.1.9
    url:     https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.9
    sha1:    dcf0582d838a73de29da273552ae79ac3098ee8b

  - name:    cf-cli
    version: 1.30.0
    url:     https://bosh.io/d/github.com/bosh-packages/cf-cli-release?v=1.30.0
    sha1:    7b4910ff8520040f3600f5d50a40aa2173777652

  - name:    haproxy
    version: 10.1.0
    url:     https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=10.1.0
    sha1:    97fbb573fc04d36c548915d8daef12a547e722d6

  - name:    routing
    version: 0.207.0
    url:     https://bosh.io/d/github.com/cloudfoundry/routing-release?v=0.207.0
    sha1:    9e703259a07f032e7ca96dca2730d0e0c2b61685

  - name: rabbitmq-metrics-emitter
    version: "0.4.0"
    url: https://github.com/starkandwayne/rabbitmq-metrics-emitter-release/releases/download/0.4.0/rabbitmq-metrics-emitter-0.4.0.tgz

  - name: loggregator-agent
    url: https://bosh.io/d/github.com/cloudfoundry/loggregator-agent-release?v=3.9
    version: "3.9"
    sha1: bf723af956a61c7b51db0ba535c871bad24dd289
