#!/bin/bash -e

IN_DIR=s3-release-blob
OUT_DIR=bosh-release

cp "${IN_DIR}/version"      "${OUT_DIR}/version"
cp "${IN_DIR}/url"          "${OUT_DIR}/url"
sha1sum "${IN_DIR}"/*.tgz > "${OUT_DIR}/sha1"
