#!/bin/bash
shopt -s nullglob
set -eu

# Genesis Kit `blueprint' Hook
#
# This script outputs the list of merge files needed to support the desired
# feature set selected by the environment parameter file.  As generated, it
# lists all *.yml files in the base, then all *.yml files in each detected
# feature directory, in the order the features are specified in the environment
# yml file.  If finer control is desired, add logic around the wants_kit_feature()
# function (takes a feature as a string, returns exit code 0 if present, non-
# zero exit code otherwise).


validate_features broker no-rmq-tls no-broker-tls external-rmq-lb \
                  broker-route-registrar manual-nats

declare -a manifests
manifests+=( manifests/base.yml
             manifests/releases.yml
             manifests/server.yml )

if want_feature "broker" ; then
  manifests+=(
    manifests/broker.yml
  )

  if ! want_feature "no-broker-tls" ; then
    manifests+=(
      manifests/addons/broker-tls.yml
    )
  fi

  if want_feature "broker-route-registrar" ; then
    manifests+=(
      manifests/addons/broker-route-registrar.yml
    )

    if ! want_feature "no-broker-tls" ; then
      manifests+=(
        manifests/addons/broker-no-tls-route-registrar.yml
      )
    fi

    if want_feature "manual-nats" ; then
      manifests+=(
        manifests/addons/manual-nats.yml
      )
    fi
  fi
fi

if want_feature "no-rmq-tls" ; then
  manifests+=(
    manifests/addons/no-rmq-tls.yml
  )
fi

if want_feature "external-rmq-lb" ; then
  manifests+=(
    manifests/addons/external-rmq-lb.yml
  )
  if want_feature "broker" ; then
    manifests+=(
      manifests/addons/external-rmq-lb-with-broker.yml
    )
  fi
fi

echo ${manifests[@]}
