#!/bin/bash
shopt -s nullglob
set -eu

# Genesis Kit `blueprint' Hook
#
# This script outputs the list of merge files needed to support the desired
# feature set selected by the environment parameter file.  As generated, it
# lists all *.yml files in the base, then all *.yml files in each detected
# feature directory, in the order the features are specified in the environment
# yml file.  If finer control is desired, add logic around the wants_kit_feature()
# function (takes a feature as a string, returns exit code 0 if present, non-
# zero exit code otherwise).


validate_features multitenant-broker rmq-no-tls

declare -a manifests
manifests+=( manifests/base.yml
             manifests/releases.yml
             manifests/server.yml )

if want_feature "multitenant-broker" ; then
  manifests+=(
    manifests/broker.yml
  )
fi

if want_feature "rmq-no-tls" ; then
  manifests+=(
    manifests/addons/rmq-no-tls.yml
  )
fi

echo ${manifests[@]}
