#!/bin/bash

echo "$GENESIS_REQUESTED_FEATURES"

if ! want_feature "no-rmq-tls" && ! want_feature "provided-rmq-cert" ; then
  echo "+rmq-tls"
fi

if ! want_feature "no-mgmt-tls" && ! want_feature "provided-mgmt-cert" ; then
  echo "+mgmt-tls"
fi

if want_feature "broker" && \
   ! want_feature "no-broker-tls" && \
   ! want_feature "provided-broker-cert" ; then
  echo "+broker-tls"
fi