---
params:
  nats_client_cert: (( param "Please provide the client certificate to use when connecting to the CF nats bus" ))
  nats_client_key:  (( param "Please provide the client private key to use when connecting to the CF nats bus" ))

meta:
  nats-tls-route-registrar-job:
    consumes:
      nats: (( prune ))
      nats-tls:
        from:       nats-tls
        deployment: (( grab meta.cf.deployment_name ))
    properties:
      nats:
        tls:
          enabled: true
          client_cert: (( grab params.nats_client_cert ))
          client_key:  (( grab params.nats_client_key ))


instance_groups:
- name: rmq-broker
  jobs:
  - name: route_registrar
    .: (( inject meta.nats-tls-route-registrar-job ))
       #    consumes:
       #      nats: (( prune ))
       #      nats-tls:
       #        from:       nats-tls
       #        deployment: (( grab meta.cf.deployment_name ))
       #    properties:
       #      nats:
       #        tls:
       #          enabled: true
       #          client_cert: (( grab params.nats_client_cert ))
       #          client_key:  (( grab params.nats_client_key ))
       #

- name: haproxy
  jobs:
  - name: route_registrar
    .: (( inject meta.nats-tls-route-registrar-job ))
      #consumes:
      #  nats: (( prune ))
      #  nats-tls:
      #    from:       nats-tls
      #    deployment: (( grab meta.cf.deployment_name ))
      #properties:
      #  nats:
      #    tls:
      #      enabled: true
      #      client_cert: (( grab params.nats_client_cert ))
      #      client_key:  (( grab params.nats_client_key ))
