instance_groups:
- name: rmq-server
  jobs:
  - name: rabbitmq-server
    properties:
      rabbitmq-server:
      - (( append ))
      - rabbitmq_prometheus
      cluster_name: (( grab genesis.env ))
