---
params:
  broker_domain: (( concat "rabbitmq-broker." meta.cf_system_domain ))
  mgmt_domain:   (( concat "rabbitmq-management." meta.cf_system_domain ))

meta:
  broker:
    protocol: https
  cf_system_domain: (( vault "secret/exodus/" meta.bosh_exodus_path "/cf:system_domain" ))

  mgmt_route_registrar_job:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from:       nats
        deployment: (( grab meta.cf_deployment ))
      nats-tls: nil
    properties:
      host:            (( grab params.rmq_domain ))
      route_registrar: (( grab meta.mgmt_domain_route ))

  mgmt_domain_route:
    routes:
      - name: (( concat meta.environment "-rabbitmq-mgmt" ))
        tls_port: 15671
        registration_interval: 20s
        server_cert_domain_san: (( grab params.mgmt_domain ))
        uris:
        - (( grab params.mgmt_domain ))

instance_groups:
- name: haproxy
  jobs:
  - (( grab meta.mgmt_route_registrar_job ))

  - name: route_registrar
    release: routing
    consumes:
      nats:
        from:       nats
        deployment: (( grab meta.cf_deployment ))
      nats-tls: nil
    properties:
      route_registrar:
        routes:
        - name: (( concat params.broker_name "-broker" ))
          tls_port: (( grab meta.broker.port ))
          registration_interval: 20s
          uris:
          - (( grab params.broker_domain ))
          server_cert_domain_san: (( grab params.broker_domain ))
      host: (( grab params.broker_domain ))

  - name: broker-registrar
    properties:
      broker:
        host: (( concat params.broker_domain ":443" ))

exodus:
  broker_url: (( concat "https://" params.broker_domain ))
  management_url: (( concat "https://" params.mgmt_domain ))

releases:
- name: routing
  .:    (( inject meta.releases.routing ))